version: '3'
services:
  omnibase:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omnibase.rule=Host(`dev.metabase.omniloy.com`)"
      - "traefik.http.routers.omnibase.entrypoints=websecure"
      - "traefik.http.routers.omnibase.tls.certResolver=letsencrypt"
      - "traefik.http.services.omnibase.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true
